#!/bin/bash
# lddcapture: A simple script to turn a binary into an appdir

# The important parts of libc that will need to be removed from the appdir
LIBC="
libanl.                                                                                                     
libc.                                                                                                       
libcidn.
libcrypt.
libdl.
libm.
libpthread.
libresolv.
librt.
libutil.
"

die() {
    echo "$1" >&2
    exit 1
}

if [ ! "$2" ]
then
    echo 'Use: lddcapture <appdir> <binary> [other libraries]'
    exit 1
fi

APPDIR="$1"
BIN="$2"
BINNAME=`basename "$BIN"`
shift; shift

mkdir "$APPDIR" || die "Failed to mkdir $APPDIR"
mkdir -p "$APPDIR/inst/bin"
mkdir -p "$APPDIR/inst/lib"

# Copy in the libraries
for i in `ldd "$BIN" | sed 's/\t/ /g' | cut -d' ' -f 4`
do
    cp -vfp "$i" "$APPDIR/inst/lib"
done
for lib in "$@"
do
    for i in `ldd "$lib" | sed 's/\t/ /g' | cut -d' ' -f 4`
    do
        cp -vfp "$i" "$APPDIR"/inst/lib
    done
    cp -vfp "$lib" "$APPDIR/inst/lib"
done

# And the binary
cp -vfp "$BIN" "$APPDIR/inst/bin"

# Now make the script to run it
echo '#!/bin/sh
# This appdir created by lddcapture.
# http://codu.org/projects/stuff/hg/index.cgi/raw-file/tip/lddcapture

APPDIR="`dirname $0`"
if [ "$LD_LIBRARY_PATH" ]
then
    LD_LIBRARY_PATH="$LD_LIBRARY_PATH:$APPDIR/inst/lib"
else
    LD_LIBRARY_PATH="$APPDIR/inst/lib"
fi
export LD_LIBRARY_PATH
exec "$APPDIR/inst/bin/'$BINNAME'" "$@"' > "$APPDIR/$BINNAME"
chmod 0755 "$APPDIR/$BINNAME"

# Remove the stupid stuff
for lib in $LIBC
do
    rm -vf "$APPDIR"/inst/lib/$lib*
done

LD_LIBRARY_PATH="$APPDIR/inst/lib" ldd "$APPDIR/inst/bin/$BINNAME"
